name: CT Shipping Lambda

on:
  push:
    branches:
      - dev
      - uat
      - prod
      # You can still include feature branches in `push` to enable CI checks, but deployments won’t run for them
      - feature/*

  pull_request:
    branches:
      - dev
      - uat
      - prod
    paths:
      - external/scripts/commercetools-shipping-lambda/**
      - .github/**

jobs:
  build-and-deploy:
    # Only run if the branch is dev, uat, or prod
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/uat' || github.ref == 'refs/heads/prod'
    environment: ${{ github.ref == 'refs/heads/uat' && 'uat' || github.ref == 'refs/heads/prod' && 'prod' || 'dev' }}

    runs-on: ubuntu-latest

    env:
      lambda_dir: external/scripts/commercetools-shipping-lambda
      function_name: commercetools-shipping-functions
      AWS_REGION: ${{ secrets.AWS_REGION }}
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Build the Lambda function
        run: |
          cd ${{ env.lambda_dir }}
          echo "Building function ${{ env.function_name }} for environment ${{ github.ref }}"
          yarn install
          yarn build
          mkdir -p build
          cd build
          zip -r deployment_package.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_region: ${{ env.AWS_REGION }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          function_name: "${{ github.ref == 'refs/heads/uat' && 'uat-' || github.ref == 'refs/heads/prod' && 'prod-' || 'dev-' }}${{ env.function_name }}"
          zip_file: ${{ env.lambda_dir }}/build/deployment_package.zip
